### ISSUE TITLE
1.16.1 is on dockerhub but the readme says 1.16.0 is current

### ISSUE THREAD

**Issue by gajowi** [OPENDAP/hyrax-docker#18]
The checksum indicates latest == 1.16.1 so I think the readme is out of date.

**Comment by jgallagher59701** [comment]
> On Feb 17, 2020, at 1:44 PM, Gareth Williams <notifications@github.com> wrote:
> 
> The checksum indicates latest == 1.16.1 so I think the readme is out of date.

Yes. Thanks for pointing this out.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
James Gallagher
jgallagher@opendap.org

**Comment by ndp-opendap** [comment]
corrected

**Comment by jgallagher59701** [comment]
Thanks


> On Feb 18, 2020, at 12:26 AM, Nathan Potter <notifications@github.com> wrote:
> 
> Closed #18.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
James Gallagher
jgallagher@opendap.org
