### ISSUE TITLE
BESCatalogDirectory - root directory /usr/share/hyrax does not exist

### ISSUE THREAD

**Issue by albertotb** [OPENDAP/hyrax-docker#28]
When I run:

```
docker run --volume /home/user:/usr/share/hyrax opendap/hyrax
```
I get the following error:

```
############################## HYRAX ##################################
Greetings, I am root.
SERVER_HELP_EMAIL is not_set
FOLLOW_SYMLINKS is not_set
Found exisiting NCWMS_BASE: https://localhost:8080
Starting the BES
Caught plugin exception during initialization of csv module:
    BESCatalogDirectory - root directory /usr/share/hyrax does not exist
Could not initialize the modules to get the log contexts.
Caught plugin exception during initialization of csv module:
    BESCatalogDirectory - root directory /usr/share/hyrax does not exist
The beslistener status is not 'BESLISTENER_RUNNING' (it is '24747808')  the master pid was not changed.
besdaemon: server cannot mount at first try (core dump). Please correct problems on the process manager /usr/bin/beslistener
BES PID file exists but process not running, cleaning up
FAILED: The BES daemon did not appear to start
```

I don't understand how this is possible, if I extract the container filesystem I can see that there is a directory called `/usr/share/hyrax`. Removing the `-volume` flag works fine, but then I cannot serve my data.

**Comment by gajowi** [comment]
Is the problem that the direction cannot be read/accessed (and the error
message is close but not quite right)?

Gareth

**Comment by albertotb** [comment]
Do you mean `/usr/share/hyrax`? I should be accessible. I'm using the official opendap/hyrax:latest image, I'm not building it myself

**Comment by ndp-opendap** [comment]
I think that ` /home/user` needs to be mounted with read permission for the "bes" user. 
Adding the permissions to the `volume` command like this:
`    --volume  /home/user:/usr/share/hyrax:ro  `
Might be the thing.

**Comment by albertotb** [comment]
I tried adding the permissions but I'm getting the same error. I'm a little
bit confused, the 'bes' user lives in the container, how would /home/user,
a directory located in the host machine, know about the "bes" user? Maybe
I'm missing something

**Comment by albertotb** [comment]
I just tried in a fresh VM and everything works fine. Clearly is an OS related problem, but a very strange one. If I can reproduce it again I will try your suggestion and report back here.

**Comment by ndp-opendap** [comment]
I will close this for now if the problem reappears please let us know!
