### ISSUE TITLE
Testing the hyrax_ncwms docker image

### ISSUE THREAD

**Issue by steingod** [OPENDAP/hyrax-docker#42]
I am testing (aggregation, configuration of THREDDS catalogues and services per dataset) the hyrax_ncwms:latest image and discovered that Godiva as supported by the image is missing BlueMarble WMS and NaturalEarth WMS background maps. NASA Blue Marble works fine. This implies that none of the Polar Stereographic map projections do have a background map (a bit unfortunate for a Norwegian user :-)). I haven't been able to find relevant information on this. Anybody that knows how to address this here?

**Comment by gajowi** [comment]
I can help explain the situation. NCWMS is a useful add on to hyrax from a
different source/author so the OPeNDAP folk can't necessarily be of direct
help. It has 2 components if you like. The main component is the wms
service which you can consume from any wms client. There is an additional
component which is an embedded wms client: Godiva3. This is nice for a
quick look at data.  By default, it gets base maps from external wms
services but unfortunately the preconfigured services sometimes break. I
understand you can override which services/maps can be listed but there may
be no obvious documentation for that. See:
https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/

You may be better off using a different wms client or consuming opendap
more directly and bypassing ncwms. You would still probably want to get
base maps from somewhere... What might work best really depends on your
experience and current needs and constraints. At least the current setup
has illustrated the sort of thing that is possible...

Best wishes,

Gareth

**Comment by steingod** [comment]
Thanks for the response. I am aware of the relation between HYRAX and nCWMS, and in particular the difference from THREDDS which I have been using for years. I will contact the ncWMS team on this as you indicate it is probably since some of the preconfigured services have moved on. Thanks for helping.
